# Generated by Django 5.0.3 on 2024-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0002_regions_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'permissions': (('can_import', 'Може да импортира'), ('can_export', 'Може да експортира')), 'verbose_name': 'Регион', 'verbose_name_plural': 'Региони'},
        ),
    ]
