# Generated by Django 5.0.3 on 2024-03-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_alter_regions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Град')),
                ('municipality_code', models.CharField(max_length=100, verbose_name='Код на община')),
                ('municipality_name', models.CharField(max_length=100, verbose_name='Име на община')),
                ('provincial_city', models.CharField(max_length=100, verbose_name='Областен град')),
                ('category', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.regions', verbose_name='Код на регион')),
            ],
            options={
                'verbose_name': 'Град',
                'verbose_name_plural': 'Градове',
                'permissions': (('can_import', 'Може да импортира'), ('can_export', 'Може да експортира')),
            },
        ),
    ]
