# Generated by Django 5.0.3 on 2024-03-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0009_custsubclass_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.regions', verbose_name='Код на регион'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.warehousetype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('municipality_code', models.CharField(max_length=20, verbose_name='Код на община')),
                ('municipality_name', models.CharField(max_length=100, verbose_name='Име на община')),
                ('provincial_city', models.CharField(max_length=100, verbose_name='Областен град')),
                ('custsubclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.custsubclass', verbose_name='Клиентски подклас')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Град',
                'verbose_name_plural': 'Градове',
            },
        ),
    ]
