# Generated by Django 5.0.3 on 2024-03-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0010_alter_office_region_alter_warehouse_type_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertype',
            name='marketTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.markettype', verbose_name='Тип Пазар'),
        ),
    ]
