# Generated by Django 5.0.3 on 2024-03-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0011_customertype_markettypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertype',
            old_name='marketTypes',
            new_name='markettypes',
        ),
        migrations.AddField(
            model_name='objtype',
            name='markettypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.markettype', verbose_name='Тип Пазар'),
        ),
    ]
