# Generated by Django 5.0.3 on 2024-03-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0013_remove_warehouse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.regions', verbose_name='Код на регион'),
        ),
    ]
