# Generated by Django 5.0.3 on 2024-03-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_asset_id_alter_asset_asset_code'),
        ('contragents', '0007_alter_contragent_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAssetDirectionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Посока на съоръжението',
                'verbose_name_plural': 'Посоки на съоръжението',
            },
        ),
        migrations.CreateModel(
            name='TransportMovementTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Тип на поръчка',
                'verbose_name_plural': 'Типове на поръчките',
            },
        ),
        migrations.CreateModel(
            name='TransportRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус на заявката')),
            ],
            options={
                'verbose_name': 'Статус на заявката',
                'verbose_name_plural': 'Статуси на заявките',
            },
        ),
        migrations.CreateModel(
            name='TransportRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_self_transport', models.BooleanField(default=False, verbose_name='Ще си нося съоръженията сам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='contragents.contragent', verbose_name='Контрагент')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportmovementtypes', verbose_name='Тип на поръчка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportrequeststatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='TransportRequestAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='assets.asset', verbose_name='Актив')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='transport.transportrequests', verbose_name='Транспортна заявка')),
            ],
            options={
                'verbose_name': 'Актив на транспортна заявка',
                'verbose_name_plural': 'Активи на транспортни заявки',
            },
        ),
    ]
