# Generated by Django 5.0.3 on 2024-03-23 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на ъпдейт')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportrequeststatus', verbose_name='Статус')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='transport.transportrequests', verbose_name='Транспортна заявка')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL, verbose_name='Ъпдейтнат от')),
            ],
            options={
                'verbose_name': 'История на статуса на транспортна заявка',
                'verbose_name_plural': 'Истории на статусите на транспортните заявки',
                'ordering': ['-updated_at'],
            },
        ),
    ]
