# Generated by Django 5.0.3 on 2024-03-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0014_alter_warehouse_region'),
        ('transport', '0003_rename_transportstatushistory_transportrequeststatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Име')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Лице за контакт')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефонен номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна поща')),
                ('gps_lat', models.FloatField(blank=True, null=True, verbose_name='GPS Ширина')),
                ('gps_long', models.FloatField(blank=True, null=True, verbose_name='GPS Дължина')),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Обща цена за километър за транспорт.', max_digits=10, verbose_name='Цена за км')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_companies', to='nomenclatures.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Транспортна компания',
                'verbose_name_plural': 'Транспортни компании',
            },
        ),
        migrations.CreateModel(
            name='TransportPriceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50, verbose_name='Тип на съоръжение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за транспорт и товаро-разтоварна дейност за единица от съответния тип съоръжение.', max_digits=10, verbose_name='Цена за тип съоръжение')),
                ('transport_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='transport.transportcompany', verbose_name='Транспортна компания')),
            ],
            options={
                'verbose_name': 'Цена за транспорт на съоръжение',
                'verbose_name_plural': 'Цени за транспорт на съоръжения',
                'unique_together': {('transport_company', 'asset_type')},
            },
        ),
    ]
