# Generated by Django 5.0.3 on 2024-03-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_id_alter_asset_asset_code'),
        ('transport', '0004_transportcompany_transportpricecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpricecompany',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Съоръжение'),
        ),
    ]
