# Generated by Django 5.0.3 on 2024-03-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_transportpricecompany_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpricecompany',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transport.transportpricecompany'),
        ),
    ]
