# Generated by Django 5.0.3 on 2024-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transportpricecompany_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportpricecompany',
            name='parent',
        ),
        migrations.AlterField(
            model_name='transportpricecompany',
            name='asset_type',
            field=models.CharField(max_length=50, verbose_name='Тип на съоръжение'),
        ),
    ]
