# Generated by Django 5.0.3 on 2024-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_remove_transportpricecompany_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpricecompany',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за тип съоръжение'),
        ),
    ]
