# Generated by Django 5.0.3 on 2024-03-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0015_assettype'),
        ('transport', '0008_alter_transportpricecompany_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpricecompany',
            name='asset_type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.assettype', verbose_name='Тип на съоръжение'),
        ),
    ]
