# Generated by Django 5.0.3 on 2024-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_transportcompanyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcompanyrequest',
            name='transport_requests',
            field=models.ManyToManyField(related_name='assigned_transport_company_requests', to='transport.transportrequests', verbose_name='Заявки за транспорт'),
        ),
    ]
