# Generated by Django 5.0.3 on 2024-03-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_alter_transportcompanyrequest_transport_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequestassets',
            name='asset_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transport', to='transport.transportassetdirectiontypes', verbose_name='Посока на съоръжението'),
        ),
        migrations.AddField(
            model_name='transportrequestassets',
            name='has_been_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
        migrations.AddField(
            model_name='transportrequestassets',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Изпълнена'),
        ),
    ]
