# Generated by Django 5.0.3 on 2024-03-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_transportrequestassets_asset_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequests',
            name='estimated_transport_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Транспортни разходи'),
        ),
    ]
