# Generated by Django 5.0.3 on 2024-03-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_transportrequests_estimated_transport_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequests',
            name='transport_company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='transport.transportcompany', verbose_name='Транспортна компания'),
            preserve_default=False,
        ),
    ]
