# Generated by Django 5.0.3 on 2024-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_transportrequests_transport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequests',
            name='price_for_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='Разход за съоръженията'),
        ),
        migrations.AddField(
            model_name='transportrequests',
            name='total_distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Тотал КМ'),
        ),
        migrations.AddField(
            model_name='transportrequests',
            name='transport_price_per_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Разход за КМ'),
        ),
    ]
