# Generated by Django 5.0.3 on 2024-03-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0014_alter_warehouse_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('bulstat', models.CharField(max_length=50, verbose_name='Булстат')),
                ('vat_number', models.CharField(max_length=50, verbose_name='ДДС номер')),
                ('attention', models.CharField(max_length=200, verbose_name='МОЛ')),
                ('email', models.EmailField(max_length=200, verbose_name='Имейл')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('bic', models.CharField(max_length=50, verbose_name='BIC')),
                ('iban', models.CharField(max_length=50, unique=True, verbose_name='IBAN')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Име на банка')),
                ('limit', models.FloatField(verbose_name='Лимит')),
                ('due_days', models.IntegerField(verbose_name='Дни за плащане')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Отстъпка')),
                ('pay_term_id', models.CharField(max_length=50, verbose_name='Условия на плащане')),
                ('blocked', models.BooleanField(default=False, verbose_name='Блокирана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадена на')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.city', verbose_name='Град')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('attention', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gps_long', models.FloatField(verbose_name='GPS дължина')),
                ('gps_lat', models.FloatField(verbose_name='GPS ширина')),
                ('chain', models.CharField(max_length=50, verbose_name='Верига')),
                ('supplier', models.CharField(max_length=50, verbose_name='Доставчик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('blocked', models.BooleanField(default=False, verbose_name='Блокиран')),
                ('distributor_code', models.CharField(max_length=50, verbose_name='Код на дистрибутор')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.city', verbose_name='Град')),
                ('company', models.ForeignKey(db_column='company_code', on_delete=django.db.models.deletion.PROTECT, related_name='contragents', to='contragents.company', verbose_name='Компания')),
                ('cust_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.custclass', verbose_name='Клас на клиента')),
                ('cust_sub_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.custsubclass', verbose_name='Подклас на клиента')),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.customertype', verbose_name='Тип на клиента')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_contragents', to=settings.AUTH_USER_MODEL, verbose_name='Търговец')),
                ('market_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.markettype', verbose_name='Тип на пазара')),
                ('obj_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.objtype', verbose_name='Тип обект')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.regions', verbose_name='Регион')),
                ('seasonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.seasonal', verbose_name='Сезонност')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
            },
        ),
    ]
