# Generated by Django 5.0.3 on 2024-03-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pay_term_id',
        ),
        migrations.AddField(
            model_name='company',
            name='pay_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Условия на плащане'),
        ),
        migrations.AlterField(
            model_name='company',
            name='attention',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='МОЛ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Име на банка'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Отстъпка'),
        ),
        migrations.AlterField(
            model_name='company',
            name='due_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни за плащане'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='company',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='limit',
            field=models.FloatField(blank=True, null=True, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ДДС номер'),
        ),
    ]
