# Generated by Django 5.0.3 on 2024-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0002_remove_company_pay_term_id_company_pay_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='attention',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отговорно лице'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='chain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Верига'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='distributor_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код на дистрибутор'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS ширина'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='gps_long',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS дължина'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доставчик'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
