# Generated by Django 5.0.3 on 2024-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0005_alter_contragent_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
