# Generated by Django 5.0.3 on 2024-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Код на актива')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Баркод')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Обект')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Създаден на')),
                ('asset_type', models.CharField(max_length=50, verbose_name='ТИП Актив')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Сериен Номер')),
                ('last_inventory', models.DateField(blank=True, null=True, verbose_name='Последна Инвентаризация')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер на Договор')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата на Договор')),
                ('decommissioned_date', models.DateField(blank=True, null=True, verbose_name='Бракуван')),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер на протокол')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата на Протокол')),
                ('complaint_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Жалба Номер')),
                ('complaint_date', models.DateField(blank=True, null=True, verbose_name='Дата Жалба')),
                ('last_repair_date', models.DateField(blank=True, null=True, verbose_name='Дата последен ремонт')),
            ],
            options={
                'verbose_name': 'Съоръжение',
                'verbose_name_plural': 'Съоръжения',
            },
        ),
    ]
