# Generated by Django 5.0.3 on 2024-03-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_warehouse_warehousetype_asset_warehouse_and_more'),
        ('nomenclatures', '0007_warehousetype_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='type',
        ),
        migrations.AlterField(
            model_name='asset',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.warehouse', verbose_name='Склад'),
        ),
        migrations.DeleteModel(
            name='WarehouseType',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
