# Generated by Django 5.0.3 on 2024-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_contragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код на актива'),
        ),
    ]
