# Generated by Django 5.0.3 on 2024-03-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_id_alter_asset_asset_code'),
        ('nomenclatures', '0015_assettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.assettype', verbose_name='Тип на съоръжение'),
        ),
    ]
