# Generated by Django 5.0.3 on 2024-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dobboxuser',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Профил', 'verbose_name_plural': 'Профил'},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Регион'),
        ),
    ]
