# Generated by Django 5.0.3 on 2024-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userdata_regions_delete_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='region',
        ),
    ]
