# Generated by Django 5.0.3 on 2024-03-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_dobboxuser_options_alter_userdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dobboxuser',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Профил', 'verbose_name_plural': 'Профил'},
        ),
    ]
