# Generated by Django 5.0.3 on 2024-03-14 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_dobboxuser_options_alter_userdata_options'),
        ('nomenclatures', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='provincial_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.city', verbose_name='Град'),
        ),
    ]
