# Generated by Django 5.0.3 on 2024-03-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_userdata_provincial_city'),
        ('nomenclatures', '0006_office_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclatures.office', verbose_name='Офис'),
        ),
    ]
