# Generated by Django 5.0.3 on 2024-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_userdata_gps_lat_remove_userdata_gps_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(default=359, max_length=20, verbose_name='Телефон'),
        ),
    ]
