# Generated by Django 5.0.3 on 2024-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(default='+359', max_length=20, verbose_name='Телефон'),
        ),
    ]
